# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-16 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('idCargo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200, null=True)),
                ('salario', models.FloatField(null=True)),
                ('competencias', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('idPartido', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200, null=True)),
                ('sede', models.CharField(max_length=200, null=True)),
                ('nomePresidente', models.CharField(max_length=200, null=True)),
                ('qtdFiliados', models.IntegerField(null=True)),
                ('dataCriacao', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Politico',
            fields=[
                ('idPolitico', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('apelido', models.CharField(max_length=200)),
                ('foto', models.FileField(upload_to='Trabalho_Implementacao_BD/')),
                ('idCargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Cargo')),
                ('idPartido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Partido')),
            ],
        ),
    ]
