BEGIN;
CREATE TABLE `crud_avaliacaopopular` (`idAvaliacaoPopular` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `nota` integer NOT NULL, `descricao` varchar(200) NOT NULL);
CREATE TABLE `crud_candidato` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `dataNascimento` date NOT NULL);
CREATE TABLE `crud_cargo` (`idCargo` integer NOT NULL PRIMARY KEY, `nome` varchar(200) NULL, `salario` double precision NULL, `competencias` varchar(200) NULL);
CREATE TABLE `crud_doador` (`idDoador` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `nome` varchar(200) NOT NULL, `valor` double precision NOT NULL);
CREATE TABLE `crud_partido` (`idPartido` integer NOT NULL PRIMARY KEY, `nome` varchar(200) NULL, `sede` varchar(200) NULL, `nomePresidente` varchar(200) NULL, `qtdFiliados` integer NULL, `dataCriacao` date NULL);
CREATE TABLE `crud_politico` (`idPolitico` integer NOT NULL PRIMARY KEY, `nome` varchar(200) NOT NULL, `apelido` varchar(200) NOT NULL, `foto` longblob NOT NULL, `idCargo_id` integer NOT NULL, `idPartido_id` integer NOT NULL);
CREATE TABLE `crud_politico_cargo` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `nroEleitora` integer NOT NULL, `tipoLocalCargo` varchar(1) NOT NULL, `nomeLocalCargo` varchar(200) NOT NULL, `idCargo_id` integer NOT NULL, `idPolitico_id` integer NOT NULL);
CREATE TABLE `crud_politico_doador` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `idDoador_id` integer NOT NULL, `idPolitico_id` integer NOT NULL);
CREATE TABLE `crud_politico_processos` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `idPolitico_id` integer NOT NULL);
CREATE TABLE `crud_politicoemmandato` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `dataPosse` date NOT NULL, `idPoliticoEmMandato_id` integer NOT NULL);
CREATE TABLE `crud_processo` (`idProcesso` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `descricao` varchar(200) NOT NULL, `dataCriacao` varchar(200) NOT NULL, `terminou` varchar(200) NOT NULL);
CREATE TABLE `crud_promessascampanha` (`idPromessasCampanha` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `plano` varchar(200) NOT NULL, `descricao` varchar(200) NOT NULL, `dataOrigem` varchar(200) NOT NULL, `idCandidato_id` integer NOT NULL);
ALTER TABLE `crud_politico_processos` ADD COLUMN `idProcesso_id` integer NOT NULL;
ALTER TABLE `crud_politico_processos` ALTER COLUMN `idProcesso_id` DROP DEFAULT;
ALTER TABLE `crud_candidato` ADD COLUMN `idCandidato_id` integer NOT NULL;
ALTER TABLE `crud_candidato` ALTER COLUMN `idCandidato_id` DROP DEFAULT;
ALTER TABLE `crud_avaliacaopopular` ADD COLUMN `idPoliticoAvaliado_id` integer NOT NULL;
ALTER TABLE `crud_avaliacaopopular` ALTER COLUMN `idPoliticoAvaliado_id` DROP DEFAULT;
ALTER TABLE `crud_politico` ADD CONSTRAINT `crud_politico_idCargo_id_2879f373b8e164d7_fk_crud_cargo_idCargo` FOREIGN KEY (`idCargo_id`) REFERENCES `crud_cargo` (`idCargo`);
ALTER TABLE `crud_politico` ADD CONSTRAINT `crud_pol_idPartido_id_394d2e0bde01007e_fk_crud_partido_idPartido` FOREIGN KEY (`idPartido_id`) REFERENCES `crud_partido` (`idPartido`);
ALTER TABLE `crud_politico_cargo` ADD CONSTRAINT `crud_politico__idCargo_id_6ad2de9f2aa5a7d8_fk_crud_cargo_idCargo` FOREIGN KEY (`idCargo_id`) REFERENCES `crud_cargo` (`idCargo`);
ALTER TABLE `crud_politico_cargo` ADD CONSTRAINT `crud__idPolitico_id_42af6aeebeeaaa4e_fk_crud_politico_idPolitico` FOREIGN KEY (`idPolitico_id`) REFERENCES `crud_politico` (`idPolitico`);
ALTER TABLE `crud_politico_doador` ADD CONSTRAINT `crud_politi_idDoador_id_42b96addfaeed678_fk_crud_doador_idDoador` FOREIGN KEY (`idDoador_id`) REFERENCES `crud_doador` (`idDoador`);
ALTER TABLE `crud_politico_doador` ADD CONSTRAINT `crud__idPolitico_id_286672c932391be0_fk_crud_politico_idPolitico` FOREIGN KEY (`idPolitico_id`) REFERENCES `crud_politico` (`idPolitico`);
ALTER TABLE `crud_politico_processos` ADD CONSTRAINT `crud_p_idPolitico_id_fd063d9c2b70157_fk_crud_politico_idPolitico` FOREIGN KEY (`idPolitico_id`) REFERENCES `crud_politico` (`idPolitico`);
ALTER TABLE `crud_politicoemmandato` ADD CONSTRAINT `D6fa192ea245fce642a7750d728aea60` FOREIGN KEY (`idPoliticoEmMandato_id`) REFERENCES `crud_politico` (`idPolitico`);
ALTER TABLE `crud_promessascampanha` ADD CONSTRAINT `crud_promes_idCandidato_id_1776664d2877efb0_fk_crud_candidato_id` FOREIGN KEY (`idCandidato_id`) REFERENCES `crud_candidato` (`id`);
CREATE INDEX `crud_politico_processos_d95d3667` ON `crud_politico_processos` (`idProcesso_id`);
ALTER TABLE `crud_politico_processos` ADD CONSTRAINT `crud_p_idProcesso_id_8f51d2305bd06d4_fk_crud_processo_idProcesso` FOREIGN KEY (`idProcesso_id`) REFERENCES `crud_processo` (`idProcesso`);
CREATE INDEX `crud_candidato_cffb0805` ON `crud_candidato` (`idCandidato_id`);
ALTER TABLE `crud_candidato` ADD CONSTRAINT `crud_idCandidato_id_3675834933129eaf_fk_crud_politico_idPolitico` FOREIGN KEY (`idCandidato_id`) REFERENCES `crud_politico` (`idPolitico`);
CREATE INDEX `crud_avaliacaopopular_3da1e9d7` ON `crud_avaliacaopopular` (`idPoliticoAvaliado_id`);
ALTER TABLE `crud_avaliacaopopular` ADD CONSTRAINT `c62eb5e05895e67633904472d1884608` FOREIGN KEY (`idPoliticoAvaliado_id`) REFERENCES `crud_politicoemmandato` (`id`);

COMMIT;
